import test from 'node:test'
import assert from 'node:assert/strict'
import { generateKeyPairSync } from 'node:crypto'
import worker, { LABELS, importKey, inspectScreenshot, rateLimitIdentifier, redact, validate } from '../src/worker.js'

const encode = (bytes) => Buffer.from(bytes).toString('base64')
const png = () => ({ type: 'image/png', data: encode([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00]) })
const jpeg = () => ({ type: 'image/jpeg', data: encode([0xff, 0xd8, 0xff, 0xe0]) })
const webp = () => ({ type: 'image/webp', data: encode([0x52, 0x49, 0x46, 0x46, 0, 0, 0, 0, 0x57, 0x45, 0x42, 0x50]) })
const pkcs1Pem = () => generateKeyPairSync('rsa', { modulusLength: 2048 }).privateKey.export({ type: 'pkcs1', format: 'pem' }).toString()

function request(body, ip = '1.2.3.4') {
  return new Request('https://support.test/', {
    method: 'POST',
    headers: { 'CF-Connecting-IP': ip, 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
}

function env(overrides = {}) {
  const kv = new Map()
  return {
    RATE_LIMIT_SALT: 'unit-test-rate-limit-salt',
    RATE_LIMIT: {
      get: async (key) => kv.get(key),
      put: async (key, value) => kv.set(key, value),
    },
    ATTACHMENT_BASE_URL: 'https://support.test/attachments',
    ATTACHMENTS: {
      put: async () => {},
      getWithMetadata: async () => ({ value: null, metadata: null }),
      delete: async () => {},
    },
    GITHUB_APP_ID: '1',
    GITHUB_INSTALLATION_ID: '2',
    GITHUB_APP_PRIVATE_KEY: 'invalid-test-key',
    ...overrides,
  }
}

test('label mapping is exact', () => {
  assert.deepEqual(LABELS.bug, ['bug', 'asr-report'])
  assert.deepEqual(LABELS.question, ['question', 'asr-support'])
  assert.deepEqual(LABELS.feature, ['enhancement', 'asr-feedback'])
})

test('imports the PKCS#1 PEM format generated by GitHub Apps', async () => {
  const key = await importKey(pkcs1Pem())
  const signature = await crypto.subtle.sign('RSASSA-PKCS1-v1_5', key, new TextEncoder().encode('test'))
  assert.ok(signature.byteLength > 0)
})

test('redacts common, JSON, authorization, and private-key secrets', () => {
  const value = redact([
    'password=hunter2 github_token=abc TGIF_password=nope Authorization: Bearer xyz',
    '{"access_token":"json-secret","session":"session-secret"}',
    '-----BEGIN PRIVATE KEY-----\nprivate-material\n-----END PRIVATE KEY-----',
  ].join('\n'))
  for (const secret of ['hunter2', 'abc', 'nope', 'xyz', 'json-secret', 'session-secret', 'private-material']) {
    assert.equal(value.includes(secret), false)
  }
})

test('validates screenshot magic bytes and claimed MIME type', () => {
  assert.equal(validate({ kind: 'bug', content: 'broken', screenshots: [png(), jpeg(), webp()] }), '')
  assert.equal(inspectScreenshot(png()).contentType, 'image/png')
  assert.match(validate({ kind: 'bug', content: 'broken', screenshots: [{ ...png(), type: 'image/jpeg' }] }), /valid PNG/)
  assert.match(validate({ kind: 'bug', content: 'broken', screenshots: [{ type: 'image/png', data: encode([1, 2, 3]) }] }), /valid PNG/)
  assert.match(validate({ kind: 'bug', content: 'broken', screenshots: [{ type: 'image/png', data: 'not base64!' }] }), /valid PNG/)
})

test('enforces decoded 2 MB screenshot limit and maximum count', () => {
  const exact = new Uint8Array(2 * 1024 * 1024)
  exact.set([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
  assert.equal(validate({ kind: 'bug', content: 'broken', screenshots: [{ type: 'image/png', data: encode(exact) }] }), '')
  const oversized = new Uint8Array(exact.length + 1)
  oversized.set(exact)
  assert.match(validate({ kind: 'bug', content: 'broken', screenshots: [{ type: 'image/png', data: encode(oversized) }] }), /2 MB/)
  assert.equal(validate({ kind: 'bug', content: 'broken', screenshots: [png(), png(), png(), png()] }), 'Too many screenshots.')
})

test('rate-limit identifiers are salted hashes and KV keys never contain raw IPs', async () => {
  const first = await rateLimitIdentifier('1.2.3.4', 'salt-one')
  const same = await rateLimitIdentifier('1.2.3.4', 'salt-one')
  const changed = await rateLimitIdentifier('1.2.3.4', 'salt-two')
  assert.equal(first, same)
  assert.notEqual(first, changed)
  assert.doesNotMatch(first, /1\.2\.3\.4/)

  const keys = []
  const testEnv = env({
    RATE_LIMIT: {
      get: async () => 0,
      put: async (key) => keys.push(key),
    },
  })
  const response = await worker.fetch(request({ kind: 'question', content: 'Need help' }), testEnv)
  assert.equal(response.status, 502)
  assert.equal(keys.length, 1)
  assert.doesNotMatch(keys[0], /1\.2\.3\.4/)
  assert.match(keys[0], /^rate:[0-9a-f]{64}:\d+$/)
})

test('worker handles CORS and rate limiting', async () => {
  const preflight = await worker.fetch(new Request('https://support.test/', { method: 'OPTIONS' }), env())
  assert.equal(preflight.status, 204)
  assert.match(preflight.headers.get('Access-Control-Allow-Methods'), /GET/)

  const identifier = await rateLimitIdentifier('1.2.3.4', 'unit-test-rate-limit-salt')
  const hour = Math.floor(Date.now() / 3600000)
  const limited = await worker.fetch(request({ kind: 'bug', content: 'broken' }), env({
    RATE_LIMIT: {
      get: async (key) => key === `rate:${identifier}:${hour}` ? 5 : 0,
      put: async () => {},
    },
  }))
  assert.equal(limited.status, 429)
})

test('serves attachments through the Worker with safe headers', async () => {
  const key = 'support/2026-09-27/12345678-1234-1234-1234-123456789abc.png'
  const response = await worker.fetch(new Request(`https://support.test/attachments/${key}`), env({
    ATTACHMENTS: {
      getWithMetadata: async (requested, options) => {
        assert.deepEqual(options, { type: 'arrayBuffer' })
        return requested === key
          ? { value: Uint8Array.from([1, 2, 3]).buffer, metadata: { contentType: 'image/png' } }
          : { value: null, metadata: null }
      },
    },
  }))
  assert.equal(response.status, 200)
  assert.equal(response.headers.get('Content-Type'), 'image/png')
  assert.equal(response.headers.get('X-Content-Type-Options'), 'nosniff')
  assert.match(response.headers.get('Cache-Control'), /immutable/)
  assert.deepEqual(new Uint8Array(await response.arrayBuffer()), Uint8Array.from([1, 2, 3]))

  const missing = await worker.fetch(new Request('https://support.test/attachments/not-safe.png'), env())
  assert.equal(missing.status, 404)
  assert.equal(missing.headers.get('X-Content-Type-Options'), 'nosniff')

  const mismatched = await worker.fetch(new Request(`https://support.test/attachments/${key}`), env({
    ATTACHMENTS: {
      getWithMetadata: async () => ({ value: Uint8Array.from([1]).buffer, metadata: { contentType: 'text/html' } }),
    },
  }))
  assert.equal(mismatched.status, 404)
  assert.equal(mismatched.headers.get('X-Content-Type-Options'), 'nosniff')
})

test('cleans up earlier screenshots after a partial upload failure', async () => {
  const uploaded = []
  const deleted = []
  const response = await worker.fetch(request({ kind: 'bug', content: 'broken', screenshots: [png(), png()] }), env({
    ATTACHMENTS: {
      put: async (key) => {
        if (uploaded.length === 1) throw new Error('second upload failed')
        uploaded.push(key)
      },
      delete: async (key) => deleted.push(key),
    },
  }))
  assert.equal(response.status, 502)
  assert.deepEqual(deleted, uploaded)
})

test('cleans up uploaded screenshots when GitHub issue creation fails', async () => {
  const uploaded = []
  const deleted = []
  const originalFetch = globalThis.fetch
  globalThis.fetch = async (url) => String(url).includes('/access_tokens')
    ? Response.json({ token: 'installation-token' })
    : new Response('issue failed', { status: 500 })
  try {
    const response = await worker.fetch(request({ kind: 'feature', content: 'Please add this', screenshots: [png()] }), env({
      GITHUB_APP_PRIVATE_KEY: pkcs1Pem(),
      ATTACHMENTS: {
        put: async (key) => uploaded.push(key),
        delete: async (key) => deleted.push(key),
      },
    }))
    assert.equal(response.status, 502)
    assert.equal(uploaded.length, 1)
    assert.deepEqual(deleted, uploaded)
  } finally {
    globalThis.fetch = originalFetch
  }
})

test('creates an issue with exact labels and retains successful attachments', async () => {
  const deleted = []
  const stored = []
  let issuePayload
  const originalFetch = globalThis.fetch
  globalThis.fetch = async (url, options) => {
    if (String(url).includes('/access_tokens')) return Response.json({ token: 'installation-token' })
    issuePayload = JSON.parse(options.body)
    return Response.json({ number: 123, html_url: 'https://github.test/issues/123' })
  }
  try {
    const response = await worker.fetch(request({ kind: 'question', content: 'How does this work?', screenshots: [png()] }), env({
      GITHUB_APP_PRIVATE_KEY: pkcs1Pem(),
      ATTACHMENTS: {
        put: async (key, value, options) => stored.push({ key, value, options }),
        delete: async (key) => deleted.push(key),
      },
    }))
    assert.equal(response.status, 200)
    assert.deepEqual(issuePayload.labels, ['question', 'asr-support'])
    assert.match(issuePayload.body, /https:\/\/support\.test\/attachments\/support\//)
    assert.deepEqual(deleted, [])
    assert.equal(stored.length, 1)
    assert.ok(stored[0].value instanceof Uint8Array)
    assert.deepEqual(stored[0].options, { metadata: { contentType: 'image/png' } })
  } finally {
    globalThis.fetch = originalFetch
  }
})

test('diagnostics are content-only and service never gathers them', () => {
  assert.equal(validate({ kind: 'question', content: 'question only' }), '')
  assert.equal(validate({ kind: 'feature', content: 'feature only' }), '')
})
