#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API = (ROOT / "asr-api.php").read_text(encoding="utf-8")
SERVER_API = (ROOT / "server/asr-api.php").read_text(encoding="utf-8")
APP = (ROOT / "src/App.tsx").read_text(encoding="utf-8")
LIVE = (ROOT / "src/lib/allscanLive.ts").read_text(encoding="utf-8")
URF = (ROOT / "scripts/asr-urf-admin.py").read_text(encoding="utf-8")
STANDALONE = (ROOT / "scripts/asr-standalone-admin.py").read_text(encoding="utf-8")
REAPPLY = (ROOT / "docker/layered-reapply.sh").read_text(encoding="utf-8")
COMPOSE = (ROOT / "docker-compose.yml").read_text(encoding="utf-8")
LIFECYCLE = (ROOT / "scripts/asr-bridge-lifecycle.py").read_text(encoding="utf-8")
ZELLO_PATH = ROOT.parent / "asl3/zello-bridge/asl_zello_bridge/zello.py"
ZELLO = ZELLO_PATH.read_text(encoding="utf-8") if ZELLO_PATH.exists() else ""
CSS = (ROOT / "src/index.css").read_text(encoding="utf-8")

def check(value: bool, message: str) -> None:
    if not value:
        raise AssertionError(message)

check(API == SERVER_API, "API copies diverged")
check("function asr_bridge_admin_capabilities" in API, "capability contract missing")
check("function asr_global_ban_policy_digest" in API, "standalone global-ban policy digest missing")
check("($cap['bridgeId'] ?? '') !== $id" in API and "($cap['healthy'] ?? false) !== true" in API, "standalone manifest identity/health checks missing")
check("is_link($path)" in API and "($stat['mode'] ?? 0) & 0022" in API and "($stat['uid'] ?? -1) !== 0" in API, "standalone manifest trust checks missing")
check("($cap['kickContract'] ?? '') === 'disconnect-until-reconnect'" in API, "standalone Kick session contract missing")
check("($cap['kickRequiresCurrentSession'] ?? false) === true" in API and "($cap['kickAllowsImmediateReconnect'] ?? false) === true" in API, "standalone Kick reconnect semantics missing")
check("($cap['banContract'] ?? '') === 'global-timed-v1'" in API and "hash_equals($policyDigest, $appliedDigest)" in API, "standalone global-ban synchronization proof missing")
check("['connect', 'disconnect', 'changeDestination']" in API, "bridge lifecycle capabilities missing")
check("array_merge($clientAdmin, ['kickClient', 'banClient', 'unbanClient', 'listBans'])" in API, "URF client capabilities missing")
check("'managementScope' => $globalAdmin ? 'asr-global' : 'bridge'" in API, "ASR-global management scope missing")
check("'clientAuthority' => $globalAdmin ? 'asr-global-ban' : 'none'" in API, "global-ban authority scope missing")
check("'banScopeLabel' => $globalAdmin ? 'GLOBAL' : ''" in API, "global ban scope label missing")
check("is_readable('/run/urf-wil/asr-admin-capabilities.json')" in API and "is_dir('/run/dmr-bridge')" in API, "URF Kick capability is not runtime-gated")
check("in_array($mode, ['dstar', 'zello'], true)" in API, "D-Star/Zello global administration capability scope missing")
check("'/run/dstar-reflector-admin'" in API and "'/run/dstar-reflector-control'" in API, "D-Star administration capability is not runtime-gated")
if ZELLO:
    check("'DSTAR': 'DSTAR'" not in URF and '"DSTAR": "DSTAR"' in URF and '"ZELLO": "ZELLO"' in URF, "D-Star/Zello helper protocols missing")
check("write_dstar_rules" in URF and "request_dstar_event" in URF, "D-Star global Ban/Kick adapter missing")
check("request_zello_kick" not in URF and "Zello does not support disconnecting a channel user." in URF, "Zello Kick helper remains")
check("[A-Z0-9_.\\/-]" in API and "[A-Z0-9_./-]" in URF, "Zello underscore identity support missing")
if ZELLO:
    check("_ke7wil_zello_is_banned" in ZELLO and "_ke7wil_zello_take_kick" not in ZELLO, "Zello Ban enforcement missing or Kick remains")
check("Recent Zello Talkers" in APP and "managedConnectedCards" in APP, "D-Star/Zello Manage Clients UI missing")
if ZELLO:
    check("kickUrfConnectedClient(identity, 'ZELLO')" not in APP, "Zello Kick button remains")
check("$mode === 'dmr'" in API and "['kickClient', 'banClient', 'unbanClient', 'listBans']" in API, "DMR client administration capability missing")
check("write_dmr_kick" in URF and "dmr-ban" in URF and "dmr-unban" in URF, "DMR Kick/Ban helper path missing")
check("request_urf_disconnect(rule, \"*\", \"ban\", False)" in URF, "global Ban does not remove active URFD sessions")
check("request_urf_disconnect(callsign, runtime_protocol, \"kick\", True)" in URF, "session-specific URFD Kick verification missing")
check("'restart'" not in API and "'recover'" not in API, "unsupported lifecycle capability exposed")
check("adminCapabilities?: BridgeAdminCapabilities" in LIVE, "frontend capability type missing")
check("bridge.adminCapabilities?.bridgeControl.includes('changeDestination')" in APP, "destination loading is not capability-driven")
check("const canConnect = bridgeCapabilities.includes('connect')" in APP, "connect rendering is not capability-driven")
check("const canDisconnect = bridgeCapabilities.includes('disconnect')" in APP, "disconnect rendering is not capability-driven")
check("clientAdmin.includes('listBans')" in APP, "Manage Clients is not capability-driven")
check("Ban is global across ASR bridges" in APP, "global-ban scope warning missing")
check("Enforcement is applied by each supported backend" in APP, "partial global-ban enforcement warning missing")
check("URFWIL Multi-Mode Bridge" in APP, "URFWIL group title regressed")
check("Kick affects only the selected current bridge session" in APP, "Kick scope semantics are not explained")
check("allscan-bridge-inline-client-actions" in APP and "allscan-bridge-inline-client-actions" in CSS, "inline client actions are missing")
check("kickBridgeConnectedClient" in APP and "kickUrfClient" in LIVE and "kickStandaloneClient" in LIVE, "bridge-aware Kick UI/API routing is missing")
check("standalone-client-kick" in LIVE and "bridgeId" in LIVE, "standalone Kick request is not bridge-specific")
check("reconcile_standalone_bans" in URF and "reconcile-all" in STANDALONE, "global Ban is not reconciled to standalone adapters")
check("disconnect-until-reconnect" in STANDALONE and "appliedPolicyDigest" in STANDALONE, "standalone acknowledgment contracts are incomplete")
check("allscan-reimagined-standalone-admin" in REAPPLY and "/run/asr-standalone-admin" in COMPOSE, "standalone administration runtime is not installed")
check("validate_admin_capabilities" in LIFECYCLE and "requires its administration capability manifest" in LIFECYCLE, "bridge installation does not require administration parity")
check("Find connected client" in APP and "urfClientFilter" in APP, "URF client search missing")
check("BANNED" in APP and "Unban" in APP, "URF ban-state workflow missing")
check("read_rules() != expected" in URF and "verified=True" in URF, "URF write verification missing")
check("function asr_urf_normalize_callsign" in API and "function asr_urf_is_service_identity" in API, "YSF service identity normalization missing")
check("['RFCKRD0', 'YSF-LIVE', 'KF0WSS', 'SRVPROB', 'M7TEST']" in API, "built-in service/probe filter is incomplete")
check("'filterServiceStations'" in API and "'filteredStations'" in API, "configurable station filtering is missing")
check("['connect','disconnect','kick','ban']" in API, "explicit administrative activity events missing")
check("allscan-urf-admin-tools" in CSS and "@media (max-width:600px)" in CSS, "responsive admin styling missing")
check(".allscan-urf-admin-scope" in CSS and "background:var(--theme-panel)" in CSS and "border:1px solid var(--theme-border)" in CSS, "admin instruction styling is not theme-driven")
check(".allscan-urf-group > .allscan-urf-access-panel" in CSS, "admin panel styling is not theme-driven")
check("font-size:15px; line-height:1.15" in CSS, "URF mini title typography is too small")
check("font-size:13px; line-height:1.25" in CSS, "URF mini row typography is too small")
check(".allscan-urf-mini-card .allscan-bridge-client-user { font-size:13px" in CSS, "URF client typography is too small")
check("@media (max-width:1400px) and (min-width:1201px)" in CSS, "compact-desktop URF grid protection missing")
check("@media (max-width:1200px) and (min-width:901px)" in CSS and "@media (max-width:1050px) and (min-width:901px)" in CSS, "tablet-landscape URF grid protection missing")
check("@media (max-width:700px)" in CSS, "phone-landscape URF grid protection missing")
check("@media (max-width:360px)" in CSS and "flex-wrap:wrap" in CSS, "narrow-phone URF header protection missing")
check("@media (max-width:520px) and (orientation:portrait)" in CSS and ".allscan-urf-group-title > .allscan-urf-mini-manage { position:static;" in CSS, "portrait Manage Clients title-overlap protection missing")
check(".allscan-urf-group > .allscan-urf-access-panel { max-width:100%; overflow:hidden;" in CSS or ".allscan-urf-access-panel { max-width:100%; overflow:hidden;" in CSS, "phone URF admin overflow protection missing")
check("dropClientChannel" in LIVE, "generic AllStar Drop Client was removed")
check("allscan-drop-client-help" in APP and "named IAX or Web client channel" in APP, "AllStar Drop Client scope regressed")
check("document.body.style.overflow = 'hidden'" in APP and "event.key === 'Escape'" in APP, "Manage Clients modal close/scroll handling missing")
check("PROTECTED_IDENTITIES" in URF and "assert_ban_allowed(rule)" in URF, "protected service identities are not enforced at the mutation layer")
check("append_audit_event" in URF and "--actor" in API, "administrator audit attribution is missing")
check("Recent bridge actions" in APP and "allscan-management-history" in CSS, "bridge administration audit history is not visible")
check("Manage Kicks & Bans" in APP and "managementTab === 'clients'" in APP and "managementTab === 'bans'" in APP, "unified connection management is missing")
check('>Manage Clients</button>' not in APP and '>Manage bans</button>' not in APP, "duplicate management buttons remain")
check('allscan-connection-node-cell' in APP and '.allscan-connection-node-cell' in CSS and '.allscan-connection-more:hover' in CSS, "compact row menu beside the node number is missing")
check("formatUrfBanRemaining" in APP and "formatUrfBanExpiration" in APP, "ban expiration display is missing")

print("Bridge Admin Controls self-test: ok")
